query Home($locale:SiteLocale = en) {
  home(locale: $locale) {
    testimonialsTitle
    testimonialsRandomButton
    testimonialsButton
    testimonials {
      text
      name
      client {
        name
        url
      }
    }
    aboutButton
    aboutTitle
    aboutText
    aboutSloganRight {
      text
    }
    aboutSloganLeft {
      text
    }
    expertiseCtaButton
    expertiseTitle
    expertiseCtaTitle
    expertiseCtaText
    expertiseShowcase {
      title
      skills {
        title
      }
    }
    projectsButton
    resumeButton
    splashButton
    splashTitle
    splashProfessions {
      text
    }
    splashExperience {
      count
      subject
    }
  }
}