query Config($locale:SiteLocale = en) {
  config(locale: $locale) {
    navResume
    navPortfolio
    socialMail
    socialLinkedin
    socialGithub
		socialTwitter
		socialTwitch
		socialPatreon
    cookiesButton
    codeButton
    languagesMenu
    copyrights
    ctaText
    ctaTitle
    policyButton
    uiToggle {
      text
    }
    closeMenu
    menuNavigationTitle
    menuSocialTitle
    menuActionsTitle
  }
  projectCounter:_allProjectsMeta {
    count
  }
  allLocales(locale: $locale) {
    title
    code
  }
  allNotices(locale: $locale, filter: {active: {eq: "true"}}) {
    id
    title
    text
    cookie
    variant
    actions {
      title
      url
    }
  }
}