query Config($locale:SiteLocale = en) {
  config(locale: $locale) {
    maintenance
    navContact
    navResume
    navPortfolio
    socialMail
    socialLinkedin
    socialGithub
    socialDribble
    cookiesButton
    codeButton
    languagesMenu
    copyrights
    ctaText
    ctaTitle
    policyButton
    uiToggle {
      text
    }
    closeMenu
    menuNavigationTitle
    menuSocialTitle
    menuActionsTitle
  }
  allLocales(locale: $locale) {
    title
    code
  }
}