query SEO($locale:SiteLocale = en) {
  _site(locale: $locale) {
    globalSeo {
      fallbackSeo {
        description
        title
        image {
          url
        }
      }
      siteName
    }
  }
}