query Portfolio($locale:SiteLocale = en) {
  portfolio(locale: $locale) {
    title
    text
    filters {
      title
    }
    wip {
      title
      id
    }
  }

  allProjects(first:50, locale: $locale) {
    slug
    splash {
      responsiveImage(
        imgixParams: {
          fit: crop,
          crop: focalpoint,
          h: 710,
          w: 710,
          auto: format
        }
      ) {
        sizes
        src
        width
        height
        alt
        title
        base64
      }
    }
    title
    categories {
      title
      id
    }
    date {
      start
      end
    }
  }  
}