query Portfolio($slug: String!, $locale: SiteLocale = en) {
  portfolio(locale: $locale) {
    servicesTitle
    dateTitle
    toolsTitle
    clientTitle
    urlTitle
    returnToPortfolioButton
    wip {
      id
      title
    }
  }

  project(filter: {slug: {eq: $slug}}, locale: $locale) {
    urls {
      title
      url
    }
    categories {
      id
      title
    }
    tools {
      title
    }
    title
    text
    splash {
      responsiveImage(imgixParams: {
        fit: max,
        auto: format,
        maxW: "3020",
      }) {
        sizes
        src
        width
        height
        alt
        title
        base64
      }
    }
    optionalText {
      title
      text
    }
    gallery {
      mimeType
      responsiveImage(imgixParams: {
        fit: min,
        auto: format,
        maxH: "710",
        maxW: "710",
      }) {
        sizes
        src
        width
        height
        alt
        title
        base64
      }
      video {
        muxPlaybackId
      }
      blurhash
      title
      alt
      width
      height
    }
    date {
      start
      end
    }
    client {
      name
    }
  }
}